insert into place (municipality_id,place_id,coordinates,photo,description) values
(1001,1,ST_PointFromText('point(-74.183333 11.283333)',4686),'https://lanzateyviaja.com/wp-content/uploads/2019/04/Parque-Natural-Tayrona-Colombia.jpg?ezimgfmt=ng:webp/ngcb15','Si te gusta la naturaleza, la aventura y las caminatas, el Parque Tayrona debe estar entre los lugares turísticos en Colombia para visitar. Está ubicado en el departamento del Magdalena, en las laderas de Sierra Nevada. Para llegar, lo mejor es que partas desde la ciudad de Santa Marta, dirección a la Guajira.'),
(1001,2,ST_PointFromText('point(-73.72 10.866667)',4686),'https://lanzateyviaja.com/wp-content/uploads/2019/04/Sierra-Nevada-Colombia.jpg?ezimgfmt=ng:webp/ngcb15','Sierra Nevada es la montaña costera más grande del mundo y está entre los 5 lugares turísticos de Colombia. Y es que sus bosques húmedos y nublados, matorrales, manglares, playas de agua claras y arena blanca lo convierten en un lugar único en todo su esplendor.'),
(1001,3,ST_PointFromText('point(-73.925192 11.037997)',4686),'https://lanzateyviaja.com/wp-content/uploads/2019/04/Ciudad-Perdida-Colombia.jpg?ezimgfmt=ng:webp/ngcb15','Entre las montañas de la Sierra Nevada en Santa Marta, en el departamento de Magdalena, se localiza la Ciudad Perdida. Un lugar construido cerca del año 700 por la extinta civilización Tayrona y uno de los mejores lugares históricos en Colombia para visitar.'),
(117,4,ST_PointFromText('point(-74.08175 4.60971)',4686),'https://lanzateyviaja.com/wp-content/uploads/2019/04/Ciudad-de-Bogota-Colombia.jpg?ezimgfmt=ng:webp/ngcb15','La próspera capital de Colombia cautiva con su arquitectura colonial y sus edificios de diseños vanguardistas. En ella tienes la oportunidad de ver los principales lugares turísticos en Bogotá ingresando por alguno de sus dos aeropuertos o por carretera desde las ciudades más cercanas del país.'),
(80,5,ST_PointFromText('point(-74.0093 5.01876)',4686),'https://lanzateyviaja.com/wp-content/uploads/2019/04/Catedral-de-Sal-Colombia.jpg?ezimgfmt=ng:webp/ngcb15','Esta maravilla se halla a 180 metros bajo tierra, es un sitio que te permite contemplar su colección de esculturas de mármol y sal, sus tres grandes naves con una iluminación mágica y conocer la cruz y el área de bosques. Es de los mejores destinos turísticos para niños donde podrás recorrer la ruta del minero y escalar el muro.'),
(290,6,ST_PointFromText('point(-75.5696 6.1901)',4686),'https://lanzateyviaja.com/wp-content/uploads/2019/04/Musio-el-Castillo-Colombia.jpg?ezimgfmt=ng:webp/ngcb15','El lugar se encuentra en el Barrio El Poblado y la mejor forma de acceder es con el transporte público de la ciudad. Al llegar te hacen un recorrido por sus 14 estancias, entre ellas la colonial, la dedicada a la música, el Salón Luís XV, el Salón de los Gobelinos, el Hall de las Azaleas, la biblioteca y los dormitorios.'),
(1001,7,ST_PointFromText('point(-74.22812 11.20145)',4686),'https://lanzateyviaja.com/wp-content/uploads/2019/04/Playa-el-Rodadero-Colombia.jpg?ezimgfmt=ng:webp/ngcb15','La playa El Rodadero en uno de los sitios turísticos más importantes de Colombia y del Caribe por sus montañas, arena blanca y aguas turquesas que son ideales para que practiques cualquier tipo de deportes acuáticos. Desde la playa cuentas con la opción de hacer un viaje en lancha de alrededor de 10 a 15 minutos hasta al Acuario y Museo de Mar.'),
(117,8,ST_PointFromText('point(-74.072 4.601919)',4686),'https://lanzateyviaja.com/wp-content/uploads/2019/04/Museo-del-Oro-Colombia.jpg?ezimgfmt=ng:webp/ngcb15','Uno de los lugares para visitar en Bogotá, Colombia es El Museo del Oro, el cual se localiza sobre el Parque de Santander. Lugar al que llegas utilizando el Transmilenio dirección Las Aguas y si vas en auto particular lo aparcas en el estacionamiento gratuito del museo.'),
(720,9,ST_PointFromText('point(-75.17 3.23)',4686),'https://lanzateyviaja.com/wp-content/uploads/2019/04/Desierto-de-Tatacoa-Colombia.jpg?ezimgfmt=ng:webp/ngcb15','El desierto de la Tatacoa se encuentra entre los 3 sitios para visitar de Colombia. Queda a tan solo 40 minutos del poblado de Neiva, zona a la que accedes con un vuelo de las principales ciudades de Colombia, o en carro particular.'),
  (585,10,ST_PointFromText('point(-77.585989 0.805333)',4686),'https://lanzateyviaja.com/wp-content/uploads/2019/04/Santuario-de-las-Lajas-Colombia.jpg?ezimgfmt=ng:webp/ngcb15','Santuario de las Lajas es considerado una de las iglesias más bonitas del mundo y uno de los mejores sitios históricos de Colombia. Se encuentra ubicado sobre un abismo en el Cañón del río Guáitara y una de sus características más resaltantes es su arquitectura gótica de piedra blanca y gris.');
